[general]
input = [
	"scratch1",
	"key1",
	"key2",
	"key3",
	"key4",
	"key5",
	"key6",
	"key7",
	"key8",
	"key9",
	"key10",
	"scratch2"
]
unit = 1080
scroll = 1

[columns]
x = 0
y = 805
align = "center"
width = [450, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 450]
height = [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]
space = [0, -450, 0, 0, 0, 0, 2, 0, 0, 0, 0, -450, 0]

[guidelines]
layer = 5
y = 0
width = [0]
height = [900]
images = ["color/white.png"]

[measureline]
height = 2
layer = 1
image = "color/white.png"

[bga]
color = [63, 63, 63, 255]
layer = -2

[keys]
padding = 40
width = [450, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 450]
height = [195, 195, 195, 195, 195, 195, 195, 195, 195, 195,195, 195]
layer = 12
pressed = [
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png"
]
released = [
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png"
]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 3
images = [
	"color/green.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/green.png"
]
[notes.LongNote]
[notes.LongNote.Head]
layer = 3
images = [
	"color/green.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/green.png"
]
[notes.LongNote.Body]
layer = 1
images = [
	"color/green.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/blue.png",
	"color/white.png",
	"color/green.png"
]

[notes.LongNote.Tail]
layer = 2
images = [
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png"
]
[notes.SoundNote]
[notes.SoundNote.Head]
layer = 3
images = [
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png",
	"color/red.png"
]


[personal_playfield]
[playfield.BlackBackground]
class = "StaticObject"
xywh = [89, 0, 902, 1080]
origin = "lane"
image = "color/black.png"
layer = 0

[playfield.BlackBackgroundKey]
class = "StaticObject"
xywh = [89, 805, 902, 275]
origin = "lane"
image = "color/black.png"
layer = 9

[playfield.StageLeft]
class = "StaticObject"
xywh = [85, 0, 4, 1080]
origin = "lane"
image = "color/whiteD.png"
layer = 10

[playfield.StageRight]
class = "StaticObject"
xywh = [991, 0, 4, 1080]
origin = "lane"
image = "color/whiteD.png"
layer = 10

[playfield.ColumnLine]
class = "StaticObject"
xywh = [539, 0, 2, 795]
origin = "lane"
image = "color/whiteD.png"
layer = 10



[playfield.JudgeLine]
class = "StaticObject"
xywh = [89, 795, 902, 20]
origin = "lane"
image = "color/red.png"
layer = 10


[playfield]
[playfield.score]
class = "ScoreDisplay"
field = "score"
format = "%07d"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "userdata/skins/PSCHC-S v3 10K toml/AldotheApache.ttf"
size = 40
xywh = [0, 0, 0.993, 1]
origin = "all"
layer = 1

[playfield.accuracy]
class = "ScoreDisplay"
field = "accuracy"
format = "%0.2f"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "userdata/skins/PSCHC-S v3 10K toml/AldotheApache.ttf"
size = 32
xywh = [0, 0.06, 0.993, 1]
origin = "all"
layer = 1

[playfield.combo]
class = "ScoreDisplay"
field = "combo"
format = "%d"
align = ["right", "bottom"]
color = [255, 255, 255, 95]
font = "userdata/skins/PSCHC-S v3 10K toml/AldotheApache.ttf"
size = 200
xywh = [0, 0, 0.993, 1]
origin = "all"
layer = 1

[playfield.timegate]
class = "ScoreDisplay"
field = "timegate"
format = "%s"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "userdata/skins/PSCHC-S v3 10K toml/AldotheApache.ttf"
size = 35
xywh = [0, 0, 1080,1080]
origin = "lane"
layer = 11

[playfield.progressBar]
class = "ProgressBar"
color = [255, 255, 255, 255]
direction = "up-down"
mode = "-"
xywh = [0, 0, 0.005, 1]
origin = "all"
layer = 1