[general]
name = "PSCHC-S v3 4K skin toml"
inputMode = "4key"
input = [
	"key1",
	"key2",
	"key3",
	"key4"
]
unit = 1080
scroll = 1

[columns]
x = 0
y = 900
align = "center"
width = [120, 120, 120, 120]
height = [40, 40, 40, 40]
space = [0, 0, 0, 0, 0]

[guidelines]
layer = 5
y = 0
width = [0]
height = [420]
images = ["color/white.png"]

[measureline]
height = 2
layer = 1
image = "color/white.png"

[bga]
color = [63, 63, 63, 255]
layer = -2

[keys]
padding = -10
width = [120, 120, 120, 120]
height = [195, 195, 195, 195, 195, 195, 195, 195, 195, 195]
layer = 12
pressed = [
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png",
	"key/pressed.png"
]
released = [
	"color/blank.png",
	"color/blank.png",
	"color/blank.png",
	"color/blank.png"
]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 3
images = [
	"color/white.png",
	"color/blue.png",
	"color/blue.png",
	"color/white.png"
]

[notes.LongNote]
[notes.LongNote.Head]
layer = 3
images = [
	"color/white.png",
	"color/blue.png",
	"color/blue.png",
	"color/white.png"
]

[notes.LongNote.Body]
layer = 1
images = [
	"color/white.png",
	"color/blue.png",
	"color/blue.png",
	"color/white.png"
]

[notes.LongNote.Tail]
layer = 2
images = [
	"color/black.png",
	"color/black.png",
	"color/black.png",
	"color/black.png"
]
[playfield]
[playfield.timegate]
class = "ScoreDisplay"
field = "timegate"
format = "%s"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "userdata/skins/PSCHC-S v3 10K toml/AldotheApache.ttf"
size = 40
xywh = [0, -150, 1080,980]
origin = "lane"
layer = 11


[personal_playfield]
[playfield.BlackBackground]
class = "StaticObject"
xywh = [300, 0, 480, 1080]
origin = "lane"
image = "color/black.png"
layer = 0

[playfield.BlackBackgroundKey]
class = "StaticObject"
xywh = [300, 900, 480, 275]
origin = "lane"
image = "color/black.png"
layer = 9

[playfield.StageLeft]
class = "StaticObject"
xywh = [296, 0, 4, 1080]
origin = "lane"
image = "color/whiteD.png"
layer = 10

[playfield.StageRight]
class = "StaticObject"
xywh = [780, 0, 4, 1080]
origin = "lane"
image = "color/whiteD.png"
layer = 10

[playfield.JudgeLine]
class = "StaticObject"
xywh = [300, 880, 480, 20]
origin = "lane"
image = "color/red.png"
layer = 10