[general]
input = [
	"key1",
	"key2",
	"key3",
	"key4",
	"key5",
	"key6",
	"key7",
	"key8",
	"key9",
	"key10",
	"key11",
	"key12",
	"key13",
	"key14",
	"key15",
	"key16",
	"key17",
	"key18"
]
unit = 480
scroll = 1

[columns]
x = 0
y = 403
align = "center"
width = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
height = [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15]
space = [0, 0, 0, 0, 1, 0, 0, 0, 0, 65, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

[guidelines]
layer = 5
y = 0
width = [0]
height = [340]
images = ["assets/white.png"]

[measureline]
height = 0
layer = 3
image = "assets/blank.png"

[bga]
color = [0, 0, 0, 0]
layer = -2

[keys]
padding = 362
width = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
height = [-285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285, -285]
layer = 17
pressed = [
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png"
]
released = [
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png"
]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 14
images = [
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
]

[notes.LongNote]
[notes.LongNote.Head]
layer = 14
images = [
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
]

[notes.LongNote.Body]
layer = 12
images = [
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
	"assets/blue.png",
	"assets/white.png",
]

[notes.LongNote.Tail]
layer = 13
images = [
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png"
]
[notes.SoundNote]
[notes.SoundNote.Head]
layer = 11
images = [
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png"
]

[personal_playfield]
[playfield.BlackBackground]
class = "StaticObject"
xywh = [-81.5, 0, 643, 480]
origin = "lane"
image = "assets/black.png"
layer = 2

[playfield.BlackKey]
class = "StaticObject"
xywh = [-81.5, 403, 643, 77]
origin = "lane"
image = "assets/key.png"
layer = 16

[playfield.ColumnLineLeft]
class = "StaticObject"
xywh = [46.5, 0, 1, 450]
origin = "lane"
image = "assets/white.png"
layer = 15

[playfield.ColumnLineMiddle]
class = "StaticObject"
xywh = [239.5, 0, 1, 450]
origin = "lane"
image = "assets/white.png"
layer = 15

[playfield.ColumnLineRight]
class = "StaticObject"
xywh = [432.5, 0, 1, 450]
origin = "lane"
image = "assets/white.png"
layer = 15

[playfield.JudgeLine]
class = "StaticObject"
xywh = [-81.5, 360, 643, 47]
origin = "lane"
image = "assets/stage.png"
layer = 10





[playfield]
[playfield.score]
class = "ScoreDisplay"
field = "score"
format = "%07d"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 40
xywh = [0, 0, 0.993, 1]
origin = "all"
layer = 1

[playfield.accuracy]
class = "ScoreDisplay"
field = "accuracy"
format = "%0.2f"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 32
xywh = [0, 0.06, 0.993, 1]
origin = "all"
layer = 1

[playfield.combo]
class = "ScoreDisplay"
field = "combo"
format = "%d"
align = ["center", "center"]
color = [200, 0, 0, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 70
xywh = [0, 0, 480, 270]
origin = "lane"
layer = 17

[playfield.timegate]
class = "ScoreDisplay"
field = "timegate"
format = "%s"
align = ["center", "center"]
color = [200, 0, 0, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 50
xywh = [0, 10, 480, 480]
origin = "lane"
layer = 17

[playfield.progressBar]
class = "ProgressBar"
color = [255, 255, 255, 255]
direction = "up-down"
mode = "-"
xywh = [0, 0, 0.005, 1]
origin = "all"
layer = 1