[general]
input = [
	"key1",
	"key2",
	"key3",
	"key4"
]
unit = 480
scroll = 1

[columns]
x = 100
y = 403
align = "left"
width = [68,68,68,68]
height = [22,22,22,22]
space = [0, 0, 0, 0, 0]	

[guidelines]
layer = 5
y = 0
width = [0]
height = [340]
images = ["assets/white.png"]

[measureline]
height = 1
layer = 3
image = "assets/white.png"

[bga]
color = [63, 63, 63, 255]
layer = -2

[keys]
padding = 362
width = [68,68,68,68]
height = [-285, -285, -285, -285]
layer = 17
pressed = [
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png",
	"assets/laser.png"
]

released = [
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png",
	"assets/blank.png"
]

[notes]
[notes.ShortNote]
[notes.ShortNote.Head]
layer = 14
images = [
	"assets/mania-note1.png",
	"assets/mania-note2.png",
	"assets/mania-note2.png",
	"assets/mania-note1.png"
]

[notes.LongNote]
[notes.LongNote.Head]
layer = 14
images = [
	"assets/mania-note1L.png",
	"assets/mania-note2L.png",
	"assets/mania-note2L.png",
	"assets/mania-note1L.png"
]

[notes.LongNote.Body]
layer = 12
images = [
	"assets/mania-note1L.png",
	"assets/mania-note2L.png",
	"assets/mania-note2L.png",
	"assets/mania-note1L.png"
]

[notes.LongNote.Tail]
layer = 13
images = [
	"assets/black.png",
	"assets/black.png",
	"assets/black.png",
	"assets/black.png"

]
[notes.SoundNote]
[notes.SoundNote.Head]
layer = 11
images = [
	"assets/red.png",
	"assets/red.png",
	"assets/red.png",
	"assets/red.png"
]

[personal_playfield]
[playfield.BlackBackground]
class = "StaticObject"
xywh = [104, 0, 272, 480]
origin = "lane"
image = "assets/black.png"
layer = 2

[playfield.BlackKey]
class = "StaticObject"
xywh = [104, 403, 272, 77]
origin = "lane"
image = "assets/key.png"
layer = 16

[playfield.JudgeLine]
class = "StaticObject"
xywh = [104, 360, 272, 47]
origin = "lane"
image = "assets/stage.png"
layer = 10






[playfield]
[playfield.score]
class = "ScoreDisplay"
field = "score"
format = "%07d"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 40
xywh = [0, 0, 0.993, 1]
origin = "all"
layer = 1

[playfield.accuracy]
class = "ScoreDisplay"
field = "accuracy"
format = "%0.2f"
align = ["right", "top"]
color = [255, 255, 255, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 32
xywh = [0, 0.06, 0.993, 1]
origin = "all"
layer = 1

[playfield.combo]
class = "ScoreDisplay"
field = "combo"
format = "%d"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 70
xywh = [0, 0, 480, 270]
origin = "lane"
layer = 17

[playfield.timegate]
class = "ScoreDisplay"
field = "timegate"
format = "%s"
align = ["center", "center"]
color = [255, 255, 255, 255]
font = "userdata/skins/Derby/AldotheApache.ttf"
size = 50
xywh = [0, 10, 480, 480]
origin = "lane"
layer = 17

[playfield.progressBar]
class = "ProgressBar"
color = [255, 255, 255, 255]
direction = "up-down"
mode = "-"
xywh = [0, 0, 0.005, 1]
origin = "all"
layer = 1